### ISSUE TITLE
Expo Devtools (Port 19002) websocket error

### ISSUE THREAD

**Issue by fabicorp** [kerbe/docker-expo#3] opened 2020-11-23 09:02 UTC
Hello!

When using your docker image with correct environment for my machine, i get mulitple error messages.

First error get thrown when trying to open localhost:19002:
![image](https://user-images.githubusercontent.com/14235438/99944166-b4eec280-2d72-11eb-9b9a-7eaa5643522c.png)

Second error gets thrown after half a minute:
![image](https://user-images.githubusercontent.com/14235438/99944239-d059cd80-2d72-11eb-9ad9-b49861a6bb5d.png)

Is this my problem or has this something to do with following: https://github.com/expo/expo-cli/issues/1081 ?

Kind regards
Fabian

**Comment by kerbe** [comment] 2021-03-13 17:18
My apologies @FabiCorp for not spotting this issue earlier.

that expo/expo-cli#1081 was solved at a time, so it shouldn't be that. It was solved way earlier than you reported that bug, unless there is regression. I haven't used expo in a while, so I need to try it out myself too. Those errors you report though looks quite much like similar problems as in 1081.

**Comment by kerbe** [comment] 2021-03-13 18:07
Alright, I tested both current working image from docker hub (7ecc2d2ab7da) as well new fresh build which contains latest expo-cli, and both works as intended.

Has these worked for you before, or is it first time setup you are trying to do?

It is possible that Windows has got update that is affecting you. At least for WSL2 there was changes in networking code, which needed more tweaks in my development machine originally.

Have you opened ports 19000 - 19002 on your local computer firewall? If your firewall is blocking connections, then you get that kind of errors. I'm able to replicate those error messages by starting expo-cli as usual, having it open in browser, and then I kill/quit expo-cli from command line. After that browser's console is flooded with similar error messages as you have been seeing. That ECONNREFUSED 127.0.0.1:19001 sounds also similar, that there is firewall blocking your connectivity.

You need to have connectivity from your LAN ip to your localhost. LAN also needs to be accessible by your mobile phone, if you are planning on using phone to run expo and debug things.

Let me know how this turns out for you.

**Comment by kerbe** [comment] 2021-03-24 00:32
Closing this issue, as there hasn't been any reply. If problem still persist, don't hesitate to comment here & ping me.

**Closed as completed by kerbe** 2021-03-24 00:32 UTC
